package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class GithubIcons
{
	private static Image load(String path)
	{
		return IconLoader.getIcon(path, GithubIcons.class);
	}

	public static final Image Github_icon = load("/org/jetbrains/plugins/github/github_icon.png"); // 16x16
}
